### ISSUE TITLE
Tables support

### ISSUE THREAD

**Issue by vb64** [vb64/markdown-pdf#13]
[Markdown](https://stackoverflow.com/questions/60322348/how-to-convert-html-mixed-markdown-to-html-docx-pdf?rq=3):

```
#header1

|TableHeader1|TableHeader2|
|--|--|
|Text1|Details 1|
|ListCell|<ul><li>FirstBullet</li><li>SecondBullet</li></ul>|

```

Render as:

![image](https://github.com/vb64/markdown-pdf/assets/8738387/1e2c1417-5953-4b33-85f3-50a174a76f8a)

Must be:

![image](https://github.com/vb64/markdown-pdf/assets/8738387/74c4cf76-0615-42ae-8f72-66a5b011b495)

**Comment by MS-Jahan** [comment]
Just found out today. Is there any progress on this or any alternative?

**Comment by vb64** [comment]
> Just found out today. Is there any progress on this or any alternative?

Will try to implement with your suggestion.

**Comment by vb64** [comment]
> Just found out today. Is there any progress on this or any alternative?

Update to [version 1.3](https://github.com/vb64/markdown-pdf/releases/tag/v.1.3) ant try it.
