### ISSUE TITLE
Support highlight？

### ISSUE THREAD

**Issue by 17Reset** [vb64/markdown-pdf#24]
When I output the entire markdown content as a pdf, there is no block highlighting and it shows the incomplete markdown, with a portion on the right side being cut

```
from markdown_pdf import MarkdownPdf
from markdown_pdf import Section


def markdown_pdf_write(file_fullname, file_contents):
    pdf = MarkdownPdf(toc_level=2)
    pdf.add_section(Section(file_contents, toc=False))

    pdf.save(file_fullname)
```

**Comment by vb64** [comment]
At the moment lib doesn't support syntax highlight. See [this topic](https://github.com/vb64/markdown-pdf/issues/12).
